# Default Environment Configuration
# These values are used when no specific environment is selected

# Global settings
namespace: "default"

# NGINX Configuration
nginx:
  name: "nginx-web"
  namespace: "web"
  image:
    tag: "1.25.3"
  service:
    type: "ClusterIP"
    port: 80
  chart:
    version: "15.14.2"
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Redis Configuration
redis:
  name: "redis-cache"
  namespace: "cache"
  auth:
    enabled: true
    password: "defaultpassword"
  persistence:
    enabled: false
  chart:
    version: "18.19.4"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Ingress Configuration
ingress:
  enabled: false
  name: "ingress-nginx"
  namespace: "ingress-nginx"
  chart:
    version: "4.8.3"
