# Production Environment Configuration
# Override values for production environment

# Global settings
namespace: "production"

# NGINX Configuration
nginx:
  name: "nginx-web-prod"
  namespace: "web-prod"
  image:
    tag: "1.25.3"
  service:
    type: "LoadBalancer"
    port: 80
  replicaCount: 3
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Redis Configuration
redis:
  name: "redis-cache-prod"
  namespace: "cache-prod"
  auth:
    enabled: true
    password: "{{ env \"REDIS_PASSWORD\" | default \"prodpassword\" }}"
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "fast-ssd"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# Ingress Configuration
ingress:
  enabled: true
  name: "ingress-nginx-prod"
  namespace: "ingress-nginx"
